kind: pipeline
type: docker
name: Pipeline-1

steps:
- name: greeting
  image: alpine/git
  pull: if-not-exists
  commands:
  - df
  - pwd
  - ls -la
  - cat .git/config
  - git config --global -l
  - git remote -v
  - echo ${DRONE_BRANCH}
  - echo ${GIT_AUTHOR_NAME} 
  - echo ${GIT_AUTHOR_EMAIL} 
  - echo ${GIT_COMMITTER_NAME} 
  - echo ${GIT_COMMITTER_EMAIL} 
  - echo ${GIT_ASKPASS}
  - echo ${SSH_ASKPASS}
- name: en
  image: alpine
  pull: if-not-exists
  commands:
  - echo hello world
- name: fr
  image: alpine
  pull: if-not-exists
  commands:
  - echo bonjour monde
  depends_on:
  - greeting
  - en

---
kind: pipeline
type: docker
name: Pipeline-2

steps:
- name: greeting
  image: alpine
  pull: if-not-exists
  commands:
  - echo hello
  - echo world
  - sleep 5
- name: en
  image: alpine
  pull: if-not-exists
  commands:
  - echo hello world
- name: fr
  image: alpine
  pull: if-not-exists
  commands:
  - echo bonjour monde

---
kind: pipeline
type: docker
name: Pipeline-3

steps:
- name: greeting
  image: alpine
  pull: if-not-exists
  commands:
  - echo hello
  - echo world
- name: en
  image: alpine
  pull: if-not-exists
  commands:
  - echo hello world
- name: fr
  image: alpine
  pull: if-not-exists
  commands:
  - echo bonjour monde
