kind: pipeline
type: docker
name: Pipeline-1

steps:
- name: greeting
  image: alpine/git
  commands:
  - ls -l
  - git add --all
  - git commit --all -m 'pushed by Drone [CI SKIP]'
  - git remote -v
  - echo ${DRONE_BRANCH}
  - echo ${GIT_AUTHOR_NAME} 
  - echo ${GIT_AUTHOR_EMAIL} 
  - echo ${GIT_COMMITTER_NAME} 
  - echo ${GIT_COMMITTER_EMAIL} 
- name: en
  image: alpine
  commands:
  - echo hello world
- name: fr
  image: alpine
  commands:
  - echo bonjour monde
  depends_on:
  - greeting
  - en

---
kind: pipeline
type: docker
name: Pipeline-2

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world
  - sleep 5
- name: en
  image: alpine
  commands:
  - echo hello world
- name: fr
  image: alpine
  commands:
  - echo bonjour monde

---
kind: pipeline
type: docker
name: Pipeline-3

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world
- name: en
  image: alpine
  commands:
  - echo hello world
- name: fr
  image: alpine
  commands:
  - echo bonjour monde
